apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.appName }}-memcached
  name: {{ .Values.appName }}-memcached
spec:
  replicas: {{ .Values.memcached.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}-memcached
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-memcached
    spec:
      containers:
      - command:
        - memcached
        - -m
        - "{{ .Values.memcached.size }}"
        image: memcached:1.5.6
        imagePullPolicy: ""
        name: seatable-memcached
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-memcached
  labels:
    app: {{ .Values.appName }}-memcached
    service: {{ .Values.appName }}-memcached
spec:
  ports:
  - port: 11211
    protocol: TCP
    targetPort: 11211
  selector:
    app: {{ .Values.appName }}-memcached
